const express = require('express');
const controller = require('../controllers/report.controller');

const router = express.Router();

router.all('/crushing-report', controller.CrushingReport);
router.all('/imagesblub', controller.Imagesblub);
router.all('/loadmodewisedata', controller.LOADMODEWISEDATA);
router.all('/loadfactorydata', controller.LOADFACTORYDATA);
router.all('/value', controller.Value);
router.all('/get-yesterdaytransit-detail', controller.GetYesterdaytransitDetail);
router.all('/get-todaytransit-detail', controller.GetTodaytransitDetail);
router.get('/analysisdata', controller.Analysisdata);
router.get('/centre-purchase', controller.CentrePurchase);
router.all('/truck-dispatch-weighed', controller.TruckDispatchWeighed);
router.get('/indent-fail-summary', controller.IndentFailSummary);
router.all('/indent-fail-summary-data', controller.IndentFailSummaryData);
router.all('/indent-faill-details', controller.IndentFaillDetails);
router.all('/indent-faill-details-data', controller.IndentFaillDetailsData);
router.get('/target-actual-misreport', controller.TargetActualMISReport);
router.all('/target-actual-misperiod-report', controller.TargetActualMISPeriodReport);
router.all('/txtdate-text-changed', controller.txtdate_TextChanged);
router.all('/next', controller.next);
router.all('/prev', controller.prev);
router.all('/driage-summary', controller.DriageSummary);
router.all('/driage-detail', controller.DriageDetail);
router.all('/driage-clerk-summary', controller.DriageClerkSummary);
router.all('/driage-clerk-detail', controller.DriageClerkDetail);
router.all('/driage-centre-detail', controller.DriageCentreDetail);
router.all('/driage-centre-clerk-detail', controller.DriageCentreClerkDetail);
router.all('/driage-clerk-centre-detail', controller.DriageClerkCentreDetail);
router.all('/budget-vsactual', controller.BudgetVSActual);
router.get('/effected-cane-area-report', controller.EffectedCaneAreaReport);
router.get('/indent-fail-summary-new', controller.IndentFailSummaryNew);
router.all('/indent-fail-summary-new-data', controller.IndentFailSummaryNewData);
router.all('/hourly-cane-arrival', controller.HourlyCaneArrival);
router.get('/centre-code', controller.CentreCode);
router.post('/centre-code-2', controller.CentreCode_2);
router.all('/loansummary-rpt', controller.LoansummaryRpt);
router.post('/loansummary-rpt-2', controller.LoansummaryRpt_2);
router.get('/survey-plot', controller.SurveyPLot);
router.post('/survey-plot-2', controller.SurveyPLot_2);
router.get('/survey-plot-details', controller.SurveyPLotDetails);
router.all('/getdisease', controller.Getdisease);
router.all('/disease-details-on-map', controller.DiseaseDetailsOnMap);
router.all('/disease-details-on-map-todate', controller.DiseaseDetailsOnMapTodate);
router.all('/suvery-check-plots-on-map-current', controller.SuveryCheckPlotsOnMapCurrent);
router.get('/checking-log-plots', controller.Checking_logPlots);
router.post('/checking-log-plots-2', controller.Checking_logPlots_2);
router.get('/checking-details-on-map', controller.CheckingDetailsOnMap);
router.get('/disease-details', controller.DiseaseDetails);
router.get('/summary-report-unit-wise', controller.SummaryReportUnitWise);
router.post('/summary-report-unit-wise-2', controller.SummaryReportUnitWise_2);

module.exports = router;
